-- Add missing columns to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS user_id VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mobileno VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS designation VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS joining_date DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS birthday DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS marital_status VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'Active';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();